/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppWatchlistRouteImport } from './routes/_app/watchlist'
import { Route as AppWatchlistIndexRouteImport } from './routes/_app/watchlist.index'
import { Route as AppWatchlistPeerIdRouteImport } from './routes/_app/watchlist.$peerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppWatchlistRoute = AppWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AppRoute,
} as any)
const AppWatchlistIndexRoute = AppWatchlistIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWatchlistRoute,
} as any)
const AppWatchlistPeerIdRoute = AppWatchlistPeerIdRouteImport.update({
  id: '/$peerId',
  path: '/$peerId',
  getParentRoute: () => AppWatchlistRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/search': typeof AppSearchRoute
  '/watchlist': typeof AppWatchlistRouteWithChildren
  '/watchlist/$peerId': typeof AppWatchlistPeerIdRoute
  '/watchlist/': typeof AppWatchlistIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/search': typeof AppSearchRoute
  '/watchlist/$peerId': typeof AppWatchlistPeerIdRoute
  '/watchlist': typeof AppWatchlistIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/watchlist': typeof AppWatchlistRouteWithChildren
  '/_app/watchlist/$peerId': typeof AppWatchlistPeerIdRoute
  '/_app/watchlist/': typeof AppWatchlistIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/search'
    | '/watchlist'
    | '/watchlist/$peerId'
    | '/watchlist/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/search' | '/watchlist/$peerId' | '/watchlist'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/search'
    | '/_app/watchlist'
    | '/_app/watchlist/$peerId'
    | '/_app/watchlist/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/watchlist': {
      id: '/_app/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AppWatchlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/watchlist/': {
      id: '/_app/watchlist/'
      path: '/'
      fullPath: '/watchlist/'
      preLoaderRoute: typeof AppWatchlistIndexRouteImport
      parentRoute: typeof AppWatchlistRoute
    }
    '/_app/watchlist/$peerId': {
      id: '/_app/watchlist/$peerId'
      path: '/$peerId'
      fullPath: '/watchlist/$peerId'
      preLoaderRoute: typeof AppWatchlistPeerIdRouteImport
      parentRoute: typeof AppWatchlistRoute
    }
  }
}

interface AppWatchlistRouteChildren {
  AppWatchlistPeerIdRoute: typeof AppWatchlistPeerIdRoute
  AppWatchlistIndexRoute: typeof AppWatchlistIndexRoute
}

const AppWatchlistRouteChildren: AppWatchlistRouteChildren = {
  AppWatchlistPeerIdRoute: AppWatchlistPeerIdRoute,
  AppWatchlistIndexRoute: AppWatchlistIndexRoute,
}

const AppWatchlistRouteWithChildren = AppWatchlistRoute._addFileChildren(
  AppWatchlistRouteChildren,
)

interface AppRouteChildren {
  AppSearchRoute: typeof AppSearchRoute
  AppWatchlistRoute: typeof AppWatchlistRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppSearchRoute: AppSearchRoute,
  AppWatchlistRoute: AppWatchlistRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
