/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppSearchIndexRouteImport } from './routes/_app/search.index'
import { Route as AppSearchPeerIdRouteImport } from './routes/_app/search.$peerId'
import { Route as AppWatchlistRouteImport } from './routes/_app/watchlist'
import { Route as AppWatchlistIndexRouteImport } from './routes/_app/watchlist.index'
import { Route as AppWatchlistPeerIdRouteImport } from './routes/_app/watchlist.$peerId'
import { Route as AppOtherRouteImport } from './routes/_app/other'
import { Route as AppOtherIndexRouteImport } from './routes/_app/other.index'
import { Route as AppOtherPeerIdRouteImport } from './routes/_app/other.$peerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchIndexRoute = AppSearchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSearchRoute,
} as any)
const AppSearchPeerIdRoute = AppSearchPeerIdRouteImport.update({
  id: '/$peerId',
  path: '/$peerId',
  getParentRoute: () => AppSearchRoute,
} as any)
const AppWatchlistRoute = AppWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AppRoute,
} as any)
const AppWatchlistIndexRoute = AppWatchlistIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWatchlistRoute,
} as any)
const AppWatchlistPeerIdRoute = AppWatchlistPeerIdRouteImport.update({
  id: '/$peerId',
  path: '/$peerId',
  getParentRoute: () => AppWatchlistRoute,
} as any)
const AppOtherRoute = AppOtherRouteImport.update({
  id: '/other',
  path: '/other',
  getParentRoute: () => AppRoute,
} as any)
const AppOtherIndexRoute = AppOtherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOtherRoute,
} as any)
const AppOtherPeerIdRoute = AppOtherPeerIdRouteImport.update({
  id: '/$peerId',
  path: '/$peerId',
  getParentRoute: () => AppOtherRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/search': typeof AppSearchRouteWithChildren
  '/search/$peerId': typeof AppSearchPeerIdRoute
  '/search/': typeof AppSearchIndexRoute
  '/watchlist': typeof AppWatchlistRouteWithChildren
  '/watchlist/$peerId': typeof AppWatchlistPeerIdRoute
  '/watchlist/': typeof AppWatchlistIndexRoute
  '/other': typeof AppOtherRouteWithChildren
  '/other/$peerId': typeof AppOtherPeerIdRoute
  '/other/': typeof AppOtherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/search/$peerId': typeof AppSearchPeerIdRoute
  '/search': typeof AppSearchIndexRoute
  '/watchlist/$peerId': typeof AppWatchlistPeerIdRoute
  '/watchlist': typeof AppWatchlistIndexRoute
  '/other/$peerId': typeof AppOtherPeerIdRoute
  '/other': typeof AppOtherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/search': typeof AppSearchRouteWithChildren
  '/_app/search/$peerId': typeof AppSearchPeerIdRoute
  '/_app/search/': typeof AppSearchIndexRoute
  '/_app/watchlist': typeof AppWatchlistRouteWithChildren
  '/_app/watchlist/$peerId': typeof AppWatchlistPeerIdRoute
  '/_app/watchlist/': typeof AppWatchlistIndexRoute
  '/_app/other': typeof AppOtherRouteWithChildren
  '/_app/other/$peerId': typeof AppOtherPeerIdRoute
  '/_app/other/': typeof AppOtherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/search'
    | '/search/$peerId'
    | '/search/'
    | '/watchlist'
    | '/watchlist/$peerId'
    | '/watchlist/'
    | '/other'
    | '/other/$peerId'
    | '/other/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/search/$peerId' | '/search' | '/watchlist/$peerId' | '/watchlist' | '/other/$peerId' | '/other'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/search'
    | '/_app/search/$peerId'
    | '/_app/search/'
    | '/_app/watchlist'
    | '/_app/watchlist/$peerId'
    | '/_app/watchlist/'
    | '/_app/other'
    | '/_app/other/$peerId'
    | '/_app/other/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search/': {
      id: '/_app/search/'
      path: '/'
      fullPath: '/search/'
      preLoaderRoute: typeof AppSearchIndexRouteImport
      parentRoute: typeof AppSearchRoute
    }
    '/_app/search/$peerId': {
      id: '/_app/search/$peerId'
      path: '/$peerId'
      fullPath: '/search/$peerId'
      preLoaderRoute: typeof AppSearchPeerIdRouteImport
      parentRoute: typeof AppSearchRoute
    }
    '/_app/watchlist': {
      id: '/_app/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AppWatchlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/watchlist/': {
      id: '/_app/watchlist/'
      path: '/'
      fullPath: '/watchlist/'
      preLoaderRoute: typeof AppWatchlistIndexRouteImport
      parentRoute: typeof AppWatchlistRoute
    }
    '/_app/watchlist/$peerId': {
      id: '/_app/watchlist/$peerId'
      path: '/$peerId'
      fullPath: '/watchlist/$peerId'
      preLoaderRoute: typeof AppWatchlistPeerIdRouteImport
      parentRoute: typeof AppWatchlistRoute
    }
    '/_app/other': {
      id: '/_app/other'
      path: '/other'
      fullPath: '/other'
      preLoaderRoute: typeof AppOtherRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/other/': {
      id: '/_app/other/'
      path: '/'
      fullPath: '/other/'
      preLoaderRoute: typeof AppOtherIndexRouteImport
      parentRoute: typeof AppOtherRoute
    }
    '/_app/other/$peerId': {
      id: '/_app/other/$peerId'
      path: '/$peerId'
      fullPath: '/other/$peerId'
      preLoaderRoute: typeof AppOtherPeerIdRouteImport
      parentRoute: typeof AppOtherRoute
    }
  }
}

interface AppSearchRouteChildren {
  AppSearchPeerIdRoute: typeof AppSearchPeerIdRoute
  AppSearchIndexRoute: typeof AppSearchIndexRoute
}

const AppSearchRouteChildren: AppSearchRouteChildren = {
  AppSearchPeerIdRoute: AppSearchPeerIdRoute,
  AppSearchIndexRoute: AppSearchIndexRoute,
}

const AppSearchRouteWithChildren = AppSearchRoute._addFileChildren(
  AppSearchRouteChildren,
)

interface AppWatchlistRouteChildren {
  AppWatchlistPeerIdRoute: typeof AppWatchlistPeerIdRoute
  AppWatchlistIndexRoute: typeof AppWatchlistIndexRoute
}

const AppWatchlistRouteChildren: AppWatchlistRouteChildren = {
  AppWatchlistPeerIdRoute: AppWatchlistPeerIdRoute,
  AppWatchlistIndexRoute: AppWatchlistIndexRoute,
}

const AppWatchlistRouteWithChildren = AppWatchlistRoute._addFileChildren(
  AppWatchlistRouteChildren,
)

interface AppOtherRouteChildren {
  AppOtherPeerIdRoute: typeof AppOtherPeerIdRoute
  AppOtherIndexRoute: typeof AppOtherIndexRoute
}

const AppOtherRouteChildren: AppOtherRouteChildren = {
  AppOtherPeerIdRoute: AppOtherPeerIdRoute,
  AppOtherIndexRoute: AppOtherIndexRoute,
}

const AppOtherRouteWithChildren = AppOtherRoute._addFileChildren(
  AppOtherRouteChildren,
)

interface AppRouteChildren {
  AppSearchRoute: typeof AppSearchRouteWithChildren
  AppWatchlistRoute: typeof AppWatchlistRouteWithChildren
  AppOtherRoute: typeof AppOtherRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppSearchRoute: AppSearchRouteWithChildren,
  AppWatchlistRoute: AppWatchlistRouteWithChildren,
  AppOtherRoute: AppOtherRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
